name: setup-node-and-install

description:
  Sets up Node.js environment and installs dependencies with automatic package manager detection (npm/pnpm/yarn),
  intelligent caching, and version detection via input, .node-version, .nvmrc, or package.json volta.node

inputs:
  node-version:
    description: Node.js version to install (e.g. '24', 'lts/*'). Precedence: node-version input > .node-version > .nvmrc > package.json volta.node.
    required: false
  cache-key-suffix:
    description: Additional suffix for cache key to enable multiple caches per workflow.
    default: ''
  install-options:
    description: Extra command-line options to pass to npm/pnpm/yarn install.
    default: ''
  working-directory:
    description: Directory containing package.json and lockfile.
    default: .

outputs:
  cache-hit:
    description: Whether the dependency cache was hit (true/false).
    value: '${{ steps.setup-node.outputs.cache-hit == 'true' && 'true' || 'false' }}'

runs:
  using: composite

  steps:
    - name: Validate environment and detect package manager
      id: detect-package-manager
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        # Validate package.json exists
        if [ ! -f "./package.json" ]; then
          echo "❌ ERROR: package.json not found in '${{ inputs.working-directory }}'"
          echo "Make sure the working-directory contains a valid Node.js project"
          exit 1
        fi

        # Detect package manager based on lockfiles (including yarn)
        if [ -f "./pnpm-lock.yaml" ]; then
          echo "package-manager=pnpm" >> $GITHUB_OUTPUT
          echo "lockfile-exists=true" >> $GITHUB_OUTPUT
          echo "lockfile-path=pnpm-lock.yaml" >> $GITHUB_OUTPUT
          echo "📦 Detected package manager: pnpm"
        elif [ -f "./yarn.lock" ]; then
          echo "package-manager=yarn" >> $GITHUB_OUTPUT
          echo "lockfile-exists=true" >> $GITHUB_OUTPUT
          echo "lockfile-path=yarn.lock" >> $GITHUB_OUTPUT
          echo "📦 Detected package manager: yarn"
        elif [ -f "./package-lock.json" ]; then
          echo "package-manager=npm" >> $GITHUB_OUTPUT
          echo "lockfile-exists=true" >> $GITHUB_OUTPUT
          echo "lockfile-path=package-lock.json" >> $GITHUB_OUTPUT
          echo "📦 Detected package manager: npm"
        else
          echo "package-manager=npm" >> $GITHUB_OUTPUT
          echo "lockfile-exists=false" >> $GITHUB_OUTPUT
          echo "lockfile-path=" >> $GITHUB_OUTPUT
          echo "📦 No lockfile found, defaulting to: npm"
        fi
      env:
        INPUT_NODE_VERSION: ${{ inputs.node-version }}

    - name: Install pnpm
      if: steps.setup.outputs.package-manager == 'pnpm'
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    # Detect Node.js version to use (input > .node-version > .nvmrc > package.json volta.node)
    - name: Detect node version
      id: detect-node-version
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        resolved_version=""

        if [ -n "${INPUT_NODE_VERSION}" ]; then
          resolved_version="$INPUT_NODE_VERSION"
          echo "📋 Using Node version from input: $resolved_version"
        elif [ -f "./.node-version" ]; then
          file_version=$(cat ./.node-version | tr -d '\n\r' | xargs)
          if [ -n "$file_version" ]; then
            resolved_version="$file_version"
            echo "📋 Using Node version from .node-version: $resolved_version"
          fi
        fi

        if [ -z "$resolved_version" ] && [ -f "./.nvmrc" ]; then
          nvmrc_version=$(cat ./.nvmrc | tr -d '\n\r' | xargs)
          if [ -n "$nvmrc_version" ]; then
            resolved_version="$nvmrc_version"
            echo "📋 Using Node version from .nvmrc: $resolved_version"
          fi
        fi

        if [ -z "$resolved_version" ]; then
          volta_node=$(jq -r '.volta.node // empty' package.json 2>/dev/null || true)
          if [ -n "$volta_node" ]; then
            resolved_version="$volta_node"
            echo "📋 Using Node version from package.json volta.node: $resolved_version"
          fi
        fi

        echo "version=$resolved_version" >> $GITHUB_OUTPUT
      env:
        INPUT_NODE_VERSION: ${{ inputs.node-version }}

    - name: Setup Node.js
      uses: actions/setup-node@v5
      id: setup-node
      with:
        # use detected package manager cache if a lockfile is present
        cache: ${{ steps.detect-package-manager.outputs.lockfile-exists == 'true' && steps.detect-package-manager.outputs.package-manager || '' }}
        cache-dependency-path: ${{ inputs.working-directory }}
        node-version: ${{ steps.detect-node-version.outputs.version }}
        registry-url: 'https://registry.npmjs.org'

    # Install dependencies with pnpm
    - name: Install dependencies with pnpm
      if: steps.detect-package-manager.outputs.package-manager == 'pnpm'
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        echo "🔧 Installing dependencies with pnpm..."
        if ! pnpm install $INPUT_INSTALL_OPTIONS; then
          echo "❌ ERROR: pnpm install failed"
          exit 1
        fi
        echo "✅ pnpm install completed successfully"
      env:
        INPUT_INSTALL_OPTIONS: ${{ inputs.install-options }}

    # Install dependencies with yarn
    - name: Install dependencies with yarn
      if: steps.setup.outputs.package-manager == 'yarn'
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        echo "🔧 Installing dependencies with yarn..."
        if ! yarn install --frozen-lockfile $INPUT_INSTALL_OPTIONS; then
          echo "❌ ERROR: yarn install failed"
          exit 1
        fi
        echo "✅ yarn install completed successfully"
      env:
        INPUT_INSTALL_OPTIONS: ${{ inputs.install-options }}

    # Install dependencies with npm (with lockfile)
    - name: Install dependencies with npm (with lockfile)
      if: steps.setup.outputs.lockfile-exists == 'true' && steps.setup.outputs.package-manager == 'npm'
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        echo "🔧 Installing dependencies with npm ci..."
        if ! npm ci --prefer-offline --no-audit $INPUT_INSTALL_OPTIONS; then
          echo "❌ ERROR: npm ci failed"
          exit 1
        fi
        echo "✅ npm ci completed successfully"
      env:
        INPUT_INSTALL_OPTIONS: ${{ inputs.install-options }}

    - name: Install dependencies with npm (without lockfile)
      if: steps.setup.outputs.lockfile-exists == 'false' && steps.setup.outputs.package-manager == 'npm'
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        echo "🔧 Installing dependencies with npm install..."
        echo "⚠️  Warning: No lockfile found, versions may vary"
        if ! npm install --no-save --prefer-offline --no-audit $INPUT_INSTALL_OPTIONS; then
          echo "❌ ERROR: npm install failed"
          exit 1
        fi
        echo "✅ npm install completed successfully"
      env:
        INPUT_INSTALL_OPTIONS: ${{ inputs.install-options }}
