name: Update Documentation

on:
  push:
    branches: [main]
    paths:
      - '*/action.yml'
      - '*/README.md'
      - bin/generate-docs.js

jobs:
  update-docs:
    name: Auto-update documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          token: ${{ secrets.GH_PAT }}

      # Dogfood our own setup-node-and-install action
      - name: Setup Node.js and install dependencies
        uses: ./setup-node-and-install
        with:
          node-version: 'lts/*'

      - name: Generate updated documentation
        run: pnpm docs:generate

      - name: Create pull request with updates
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.GH_PAT }}
          commit-message: 'docs: auto-update documentation with latest action metadata'
          title: >-
            docs: auto-update documentation with latest action metadata
          body: Automated documentation update.
          branch: automation/update-docs
          delete-branch: true
          add-paths: |
            README.md
            */README.md
